package;

/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

// @formatter:off
class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var BushRustle:String = "event:/SFX/Bush/BushRustle";
    public static inline var FishingRodCharge:String = "event:/SFX/FishingRod/FishingRodCharge";
    public static inline var FishingRodCharge2:String = "event:/SFX/FishingRod/FishingRodCharge2";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var New:String = "event:/SFX/New";
    public static inline var PlayerStepDirt:String = "event:/SFX/Player/PlayerStepDirt";
    public static inline var PlayerStepGrass:String = "event:/SFX/Player/PlayerStepGrass";
    public static inline var PlayerStepWater:String = "event:/SFX/Player/PlayerStepWater";
    public static inline var RockSplash:String = "event:/SFX/Rock/RockSplash";
    public static inline var WeedsBurst:String = "event:/SFX/Weeds/WeedsBurst";
}
class FmodBus {
    public static inline var Master:String = "bus:/";
    public static inline var Music:String = "bus:/Music";
    public static inline var SFX:String = "bus:/SFX";
}
